<a href="https://colab.research.google.com/github/AnsilNaseem/ansil/blob/main/DataPreprocessingAssignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Assignment

In [1]:
# importing libraries
import numpy as nm
import matplotlib.pyplot as mtp
import pandas as pd

# Uploading datasets

1.From Upload

In [2]:
#importing datasets from file upload

from google.colab import files

uploaded = files.upload()

for fn in uploaded.keys():
  print('\nDataset "{name}" Uploaded - {length} bytes'.format(
      name=fn, length=len(uploaded[fn])))

2.From Google Drive File

In [3]:
from google.colab import drive
drive.mount('/gdrive')

%cd /gdrive/MyDrive/S6_Data_Analytics
%ls

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).
/gdrive/MyDrive/S6_Data_Analytics
 AssignmentDataset.csv          ' oop lab.doc'              wcs_specieslist.csv
 main.txt                       'wcs_specieslist (1).csv'
 MODIS_C6_1_South_Asia_24h.csv  'wcs_specieslist (2).csv'


In [4]:

import pandas as pd
data_set= pd.read_csv('AssignmentDataset.csv')

# Extracting variables

In [5]:
#Extracting Independent Variable
x= data_set.iloc[:, :-1].values
x

array([['India', 38.0, 68000.0],
       ['France', 43.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['France', 48.0, 65000.0],
       ['Germany', 40.0, nan],
       ['India', 35.0, 58000.0],
       ['Germany', nan, 53000.0],
       ['France', 49.0, 79000.0],
       ['India', 50.0, 88000.0],
       ['France', 37.0, 77000.0]], dtype=object)

In [6]:
#Extracting Dependent variable
y= data_set.iloc[:, 3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

# Missing Data

In [7]:
#handling missing data(Replacing missing data with the mean value)

from sklearn.impute import SimpleImputer
#from sklearn.preprocessing import Imputer was deprecated with scikit-learn v0.20.4 and removed as of v0.22.2.
imputer= SimpleImputer(missing_values =nm.nan, strategy='mean')
#Fitting imputer object to the independent varibles x.
imputer= imputer.fit(x[:, 1:3])
#Replacing missing data with the calculated mean value
x[:, 1:3]= imputer.transform(x[:, 1:3])
x

array([['India', 38.0, 68000.0],
       ['France', 43.0, 45000.0],
       ['Germany', 30.0, 54000.0],
       ['France', 48.0, 65000.0],
       ['Germany', 40.0, 65222.22222222222],
       ['India', 35.0, 58000.0],
       ['Germany', 41.111111111111114, 53000.0],
       ['France', 49.0, 79000.0],
       ['India', 50.0, 88000.0],
       ['France', 37.0, 77000.0]], dtype=object)

In [8]:
#Converting Categorical Variables
#for Country Variable

from sklearn.preprocessing import LabelEncoder, OneHotEncoder
label_encoder_x= LabelEncoder()
x[:, 0]= label_encoder_x.fit_transform(x[:, 0])

In [9]:
#Encoding for dummy variables
from sklearn.compose import ColumnTransformer
ct = ColumnTransformer([('country', OneHotEncoder(),[0])],remainder='passthrough')
x=ct.fit_transform(x)
x

array([[0.0, 0.0, 1.0, 38.0, 68000.0],
       [1.0, 0.0, 0.0, 43.0, 45000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [1.0, 0.0, 0.0, 48.0, 65000.0],
       [0.0, 1.0, 0.0, 40.0, 65222.22222222222],
       [0.0, 0.0, 1.0, 35.0, 58000.0],
       [0.0, 1.0, 0.0, 41.111111111111114, 53000.0],
       [1.0, 0.0, 0.0, 49.0, 79000.0],
       [0.0, 0.0, 1.0, 50.0, 88000.0],
       [1.0, 0.0, 0.0, 37.0, 77000.0]], dtype=object)

In [10]:
#encoding for purchased variable
labelencoder_y= LabelEncoder()
y= labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

# Training and Test Set

In [11]:
# Splitting the dataset into training and test set.
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x, y, test_size= 0.2, random_state=0)

In [12]:
x_train

array([[0.0, 1.0, 0.0, 40.0, 65222.22222222222],
       [1.0, 0.0, 0.0, 37.0, 77000.0],
       [1.0, 0.0, 0.0, 43.0, 45000.0],
       [0.0, 1.0, 0.0, 41.111111111111114, 53000.0],
       [1.0, 0.0, 0.0, 49.0, 79000.0],
       [1.0, 0.0, 0.0, 48.0, 65000.0],
       [0.0, 0.0, 1.0, 38.0, 68000.0],
       [0.0, 0.0, 1.0, 35.0, 58000.0]], dtype=object)

In [13]:
x_test

array([[0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 50.0, 88000.0]], dtype=object)

In [14]:
y_train

array([1, 1, 1, 0, 1, 0, 0, 1])

In [15]:
y_test

array([0, 0])

# Feature Scaling

In [16]:
#Feature Scaling of datasets
from sklearn.preprocessing import StandardScaler
st_x= StandardScaler()
x_train= st_x.fit_transform(x_train)
x_test= st_x.transform(x_test)

In [17]:
x_test

array([[-1.        ,  1.73205081, -0.57735027, -2.41578041, -0.90681902],
       [-1.        , -0.57735027,  1.73205081,  1.82656568,  2.24643804]])